# Generated by Django 4.0.4 on 2022-05-04 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=25)),
                ('fecha_elab_medicamento', models.DateField()),
                ('fecha_venc_medicamento', models.DateField()),
                ('cantidad_medicamento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('run_medico', models.IntegerField()),
                ('dv_medico', models.IntegerField()),
                ('nombre_medico', models.CharField(max_length=25)),
                ('apellido_medico', models.CharField(max_length=25)),
                ('sexo_medico', models.CharField(max_length=1)),
                ('edad_medico', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('run_paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_paciente', models.IntegerField()),
                ('nombre_paciente', models.CharField(max_length=25)),
                ('apellido_paciente', models.CharField(max_length=25)),
                ('edad_paciente', models.IntegerField()),
                ('sexo_paciente', models.CharField(max_length=1)),
                ('direccion_paciente', models.CharField(max_length=60)),
                ('mail_paciente', models.CharField(max_length=25)),
                ('numero_telefonico', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_llegada',
            fields=[
                ('id_stock_llegada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_llegada', models.DateField()),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_actual',
            fields=[
                ('id_stock_actual', models.AutoField(primary_key=True, serialize=False)),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Receta_medica',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('prescripcion_receta', models.TextField(max_length=200)),
                ('fecha_receta', models.DateField()),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.medicamento')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.medico')),
                ('run_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha_paciente',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_retiro', models.DateField()),
                ('id_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.receta_medica')),
                ('run_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Farmaceutico',
            fields=[
                ('id_farmaceutico', models.AutoField(primary_key=True, serialize=False)),
                ('run_farmaceutico', models.IntegerField()),
                ('dv_farmaceutico', models.IntegerField()),
                ('nombre_farmceutico', models.CharField(max_length=25)),
                ('apellido_farmaceutico', models.CharField(max_length=25)),
                ('edad_farmaceutico', models.IntegerField()),
                ('sexo_farmaceutico', models.CharField(max_length=1)),
                ('id_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ficha_paciente')),
                ('id_stock_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.stock_actual')),
                ('id_stock_llegada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.stock_llegada')),
            ],
        ),
    ]
