# Generated by Django 4.0.4 on 2022-05-05 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='img_paciente',
            field=models.ImageField(null=True, upload_to='img_paciente'),
        ),
        migrations.AlterField(
            model_name='farmaceutico',
            name='id_ficha',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.ficha_paciente'),
        ),
        migrations.AlterField(
            model_name='farmaceutico',
            name='id_stock_actual',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.stock_actual'),
        ),
        migrations.AlterField(
            model_name='farmaceutico',
            name='id_stock_llegada',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.stock_llegada'),
        ),
        migrations.AlterField(
            model_name='ficha_paciente',
            name='id_receta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.receta_medica'),
        ),
        migrations.AlterField(
            model_name='ficha_paciente',
            name='run_paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.paciente'),
        ),
        migrations.AlterField(
            model_name='receta_medica',
            name='id_medicamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.medicamento'),
        ),
        migrations.AlterField(
            model_name='receta_medica',
            name='id_medico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.medico'),
        ),
        migrations.AlterField(
            model_name='receta_medica',
            name='run_paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.paciente'),
        ),
        migrations.AlterField(
            model_name='stock_actual',
            name='id_medicamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.medicamento'),
        ),
        migrations.AlterField(
            model_name='stock_llegada',
            name='id_medicamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.medicamento'),
        ),
    ]
