# Generated by Django 4.0.4 on 2022-05-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='is_farmaceutico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customusuario',
            name='is_medico',
            field=models.BooleanField(default=False),
        ),
    ]
