# Generated by Django 4.0.4 on 2022-05-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo_paciente',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='personal',
            name='sexo_personal',
            field=models.BooleanField(),
        ),
    ]
