# Generated by Django 4.0.4 on 2022-05-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_paciente_sexo_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='sexo_paciente',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='sexo_personal',
        ),
        migrations.AddField(
            model_name='paciente',
            name='is_femenino',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='is_masculino',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='is_femenino',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='is_masculino',
            field=models.BooleanField(default=False),
        ),
    ]
