# Generated by Django 4.0.4 on 2022-05-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_customusuario_is_farmaceutico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
